### ISSUE TITLE
This version of mac os x is not supported.

### ISSUE THREAD

**Issue by saujix** [Keylem/ThinkPad-E14-Gen3-AMD-Ryzen-5-5500U-Hackintosh#7]
Tried resetting nvram.
In the opencore menu.
on macos mojave

**Comment by saujix** [comment]
![Uploading 20230618_084946.jpg…]()

**Comment by Keylem** [comment]
Mojave is not supported (And will never be ) by the NootedRed.kext, use Big Sur RECOVERY as described. If it won't work, try to troubleshoot it by looking at this guide --> https://dortania.github.io/OpenCore-Install-Guide/
